x = input('Digite algo:\n')
print('O tipo primitivo desse valor e:', type(x))
print('Só tem espaços? ', x.isspace())
print('É um numero?', x.isnumeric())
print('É alfabetico?', x.isalpha())
print('É alphanumerioca?', x.isalnum())
print('Esta em maiusculo?', x.isupper())
print('Esta em minusculo?', x.islower())
print('Esta capitalizada?', x.istitle())
